### ISSUE TITLE
management-console svg show Issues

### ISSUE THREAD

**Issue by ChangMuChen** [apache/incubator-kie-kogito-apps#1009]
![image](https://user-images.githubusercontent.com/17783347/131979832-3aa2093a-bc39-485d-b32a-7b0b83663179.png)
As shown above, when I drag an SVG, dashed lines appear along the border of the SVG .

**Comment by nmirasch** [comment]
Hello @ChangMuChen, First thing to check would be the content of the process export to svg is being used. Just to verify if that's an issue of the process export to the svg or related with svg processing to show the execution path (active/complete nodes)? Could mind to  paste that svg itself, please? Thanks!

**Comment by ChangMuChen** [comment]
[processSVG.zip](https://github.com/kiegroup/kogito-apps/files/7119054/processSVG.zip)
@nmirasch

**Comment by nmirasch** [comment]
@ChangMuChen  Thanks!
In a first look I don't see any issue with the export (no dashed lines there) . To be able to explore if that happens in the execution path 'paint' phase, could be possible to pass me the reproducer?, just to give it a try and see what can be happening there.

**Comment by nmirasch** [comment]
@ChangMuChen Hello again, after a second read of the issue....It seems the problem is related to see the limit of the svg  as dashed line. That's the way the component shows the border of the SVG when the zoom or exploration arrives to the limit. We can explore the svg visualization component to hide them if it's necessary even the limits would be useful to the user to explore the diagram. Let us know what you think. Thanks!!

**Comment by ricardozanini** [comment]
Closing as stale issue.
